name: Robo-Sync

on:
  # Manual or schedule
  workflow_dispatch:

  schedule:
    - cron: '7 5 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: git-sync nppThemes
        uses: wei/git-sync@v3
        with:
          source_repo: "notepad-plus-plus/nppThemes"
          source_branch: "main"
          destination_repo: "git@github.com:pryrt/nppThemes"
          destination_branch: "main"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        continue-on-error: true
      - name: git-sync userDefinedLanguages
        uses: wei/git-sync@v3
        with:
          source_repo: "notepad-plus-plus/userDefinedLanguages"
          source_branch: "master"
          destination_repo: "git@github.com:pryrt/userDefinedLanguages"
          destination_branch: "master"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        continue-on-error: true
      - name: git-sync npp-usermanual
        uses: wei/git-sync@v3
        with:
          source_repo: "notepad-plus-plus/npp-usermanual"
          source_branch: "master"
          destination_repo: "git@github.com:pryrt/npp-usermanual"
          destination_branch: "master"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        continue-on-error: true
      - name: git-sync nppPluginList
        uses: wei/git-sync@v3
        with:
          source_repo: "notepad-plus-plus/nppPluginList"
          source_branch: "master"
          destination_repo: "git@github.com:pryrt/nppPluginList"
          destination_branch: "master"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        continue-on-error: true
      - name: git-sync notepad-plus-plus
        uses: wei/git-sync@v3
        with:
          source_repo: "notepad-plus-plus/notepad-plus-plus"
          source_branch: "master"
          destination_repo: "git@github.com:pryrt/notepad-plus-plus"
          destination_branch: "master"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        continue-on-error: true
      - name: git-sync plugintemplate
        uses: wei/git-sync@v3
        with:
          source_repo: "npp-plugins/plugintemplate"
          source_branch: "master"
          destination_repo: "git@github.com:pryrt/plugintemplate"
          destination_branch: "master"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        continue-on-error: true
      - name: git-sync plugindemo
        uses: wei/git-sync@v3
        with:
          source_repo: "npp-plugins/plugindemo"
          source_branch: "master"
          destination_repo: "git@github.com:pryrt/plugindemo"
          destination_branch: "master"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        continue-on-error: true
