# This is a basic workflow to help you get started with Actions

name: Robo-Sync

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # TODO: set up a cron, as well

jobs:
  # This workflow contains a single job called "build"
  sync:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: git-sync nppThemes
        uses: wei/git-sync@v3
        with:
          source_repo: "notepad-plus-plus/nppThemes"
          source_branch: "main"
          destination_repo: "git@github.com:pryrt/nppThemes"
          destination_branch: "main"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        continue-on-error: true
      - name: git-sync userDefinedLanguages
        uses: wei/git-sync@v3
        with:
          source_repo: "notepad-plus-plus/userDefinedLanguages"
          source_branch: "main"
          destination_repo: "git@github.com:pryrt/userDefinedLanguages"
          destination_branch: "main"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        continue-on-error: true
      - name: git-sync npp-usermanual
        uses: wei/git-sync@v3
        with:
          source_repo: "notepad-plus-plus/npp-usermanual"
          source_branch: "main"
          destination_repo: "git@github.com:pryrt/npp-usermanual"
          destination_branch: "main"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        continue-on-error: true
      - name: git-sync nppPluginList
        uses: wei/git-sync@v3
        with:
          source_repo: "notepad-plus-plus/nppPluginList"
          source_branch: "main"
          destination_repo: "git@github.com:pryrt/nppPluginList"
          destination_branch: "main"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        continue-on-error: true
      - name: git-sync notepad-plus-plus
        uses: wei/git-sync@v3
        with:
          source_repo: "notepad-plus-plus/notepad-plus-plus"
          source_branch: "main"
          destination_repo: "git@github.com:pryrt/notepad-plus-plus"
          destination_branch: "main"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        continue-on-error: true
      - name: git-sync plugintemplate
        uses: wei/git-sync@v3
        with:
          source_repo: "npp-plugins/plugintemplate"
          source_branch: "main"
          destination_repo: "git@github.com:pryrt/plugintemplate"
          destination_branch: "main"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        continue-on-error: true
      - name: git-sync plugindemo
        uses: wei/git-sync@v3
        with:
          source_repo: "npp-plugins/plugindemo"
          source_branch: "main"
          destination_repo: "git@github.com:pryrt/plugindemo"
          destination_branch: "main"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        continue-on-error: true
